const log = console.log;
const cadre = PIXI.Sprite.fromImage('images/Cadre_1.png');
cadre.interactive = true;
cadre.buttonMode = true;
cadre.anchor.set(0.5);
cadre.width  = 400;
cadre.height = 350;
cadre.x = 400;
cadre.y = 300;
app.stage.addChild(cadre);